@extends('layouts.app')
@section('content')
    <login
        email-placeholder-default="E-mail"
        password-placeholder-default="Password"
        route-login="{{route('login')}}"
        route-register="{{route('register')}}"
    ></login>
@endsection
