swagger: "2.0"
info:
  description: "API Documentation for Apollo"
  version: "Alpha"
  title: "Apollo"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "127.0.0.1:8000"
basePath: "/api"
tags:
- name: "User"
  description: "Documentation for users API"
schemes:
- "http"
paths:
  /validateregister:
    get:
      tags:
      - "User"
      summary: "Validate a user input for register"
      description: ""
      operationId: "validateUserRegister"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "query"
        name: "type"
        enum: ["email", "password", "birthloc"]
        type: "string"
        required: true

      - in: "query"
        name: "email"
        type: "string"
        required: true

      - in: "query"
        name: "firstName"
        type: "string"
        required: true

      - in: "query"
        name: "lastName"
        type: "string"
        required: true

      - in: "query"
        name: "password"
        type: "string"
        required: true

      - in: "query"
        name: "password_confirmation"
        type: "string"
        required: true

      - in: "query"
        name: "birthDay"
        type: "integer"
        required: true

      - in: "query"
        name: "birthMonth"
        type: "integer"
        required: true

      - in: "query"
        name: "birthYear"
        type: "integer"
        required: true

      - in: "query"
        name: "location"
        type: "string"
        required: true

      responses:
        500:
          description: "Internal"
        200:
          description: "Success"
  /validate:
    get:
      tags:
      -  "User"
      summary: "Validate a user input for login"
      description: ""
      operationId: "validateUserInput"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "query"
        name: "type"
        enum: ["email", "final"]
        type: "string"
        required: true

      - in: "query"
        name: "email"
        type: "string"
        required: true

      - in: "query"
        name: "password"
        type: "string"
        required: true
      responses:
        500:
          description: "Internal"
        200:
          description: "Success"
